Add functionality UAB-18666
celtra/custom-ui-extension-template pull request #1
Opened 2024-04-23 14:38 UTC by sandirezonjaceltra

https://celtra.atlassian.net/browse/UAB-18666

2024-05-08 07:54 UTC, mihak requested changes
Did not finish the review just providing initial feedback to unblock fixes. Check Jira card for other comments.

2024-05-08 07:54 UTC, mihak commented on README.md
> +3. Host the `index.html` file. As it's a simple html, you can do this in multiple ways - from creating own server to uploading it anywhere that allows file hosting and download. You will need the url
This is a big no no:
* we don't want to expose this to the outside world that they can host files with us
* if/when we introduce deleting blobs on S3 we can delete those without knowing it's used anywhere

This can be used internally but it should not be as part of the documentation.

2024-05-08 07:54 UTC, mihak commented on README.md
> +	Go to Overview on Eagle, click on Export button and under Distribute you should see your extension.
Eagle => Scaling Studio

2024-05-08 07:54 UTC, mihak commented on README.md
> +Use the url you get when running `npm run dev` and use it as a host url to create the extension on account. See [here](#uploading-extension-to-the-platform).
[here] => [Uploading extension to the platform]

2024-05-08 09:33 UTC, mihak requested changes

2024-05-08 09:33 UTC, mihak commented on src/main.ts
> +import '@mdi/font/css/materialdesignicons.css'
Do we need those?

2024-05-08 09:33 UTC, mihak commented on src/main.ts
> +  // First time setting the attributes
`First time setting the attributes from persistent storage.` maybe?

2024-05-08 09:33 UTC, mihak commented on src/main.ts
> +  // First time setting the attributes
Please go through all comments and fix them to be consistent starting with upper case and ending with a period.

2024-05-08 09:33 UTC, mihak commented on src/constants.ts
> +    iconUrl: 'https://cache-ssl.celtra.io/api/blobs/128edf2e5f2a9bc4b74c51c1452735fb41595931ea2707e1d84a5b0a05b87ff5/icon.png', // Url to icon needs to be externally available
We should not have any links to blobs in the code. I guess we can put it in public dir in UAB if needed.

2024-05-08 09:33 UTC, mihak commented on src/App.vue
> +import { computed, onMounted, onBeforeUnmount } from 'vue'
Hmm.. maybe `export` is a bit confusing name. What about: 
* `InProgressPanel` or `LoadingPanel`
* and then simply `InfoPanel`

Export might imply that we're exporting this somewhere and not just getting the output data.

2024-05-08 09:33 UTC, mihak commented on src/App.vue
> +    <export-info-panel v-else-if="showExportInfoPanel" />
Do we need `showExportInfoPanel`? This could simple be `v-else` right?

2024-05-08 09:33 UTC, mihak commented on src/views/ExportInfoPanel.vue
> +  <v-expansion-panels class="info">
Do we need info section? I see it's in the design I'm just curious what's the value? At least we can show the format label i guess.
![Screenshot 2024-05-08 at 11 11 09](https://github.com/celtra/custom-ui-extension-template/assets/7932199/5f19fbd3-4f6a-42c7-871d-9512a27a13d6)

Let's discuss on a weekly today.

2024-05-08 09:33 UTC, mihak commented on src/views/ExportInfoPanel.vue
> +  console.error(attributesStore.outputAttributes, outputId, name)
Remove.

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/store.ts
> +        this.designFileContentBlobHash = outputs[0].designFile.contentBlobHash ?? null
Can `contentBlobHash` be null?

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/store.ts
> +        this.designFileContentBlobHash = outputs[0].designFile.contentBlobHash ?? null
Also, let's add a comment why `contentBlobHash` is needed.

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/store.ts
> +    async fetchOutputs (caller: string): Promise<void> {
I don't see this being used anywhere.

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/types.ts
> +  exportFailed: string | null
`exportFailedMessage`

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/types.ts
> +  allOutputsCount: number
This should not be in state. This can be a getter that returns `outputs.length`.

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/store.ts
> +    outputInfo (): {
`outputsInfo` or `mappedOutputs` or something that says its array of outputs.

2024-05-08 09:33 UTC, mihak commented on src/views/ExportInfoPanel.vue
> +                  HTML preview not available.
Should we even allow HTML in supported formats? It could be useful for setting attributes but maybe we can just skip it. Let's confirm later on a call.

2024-05-08 09:33 UTC, mihak commented on src/stores/export-api/utils.ts
> +    }
adServer is always null right?

2024-05-08 09:33 UTC, mihak commented on src/stores/attributes/store.ts
> +            this.flushUpdateAttributes()
This is a weird name. Can we simply name this `setAttributes`?

2024-05-08 09:33 UTC, mihak commented on src/stores/attributes/store.ts
> +                console.error('getstoreage', outputAttributesRegistrationOptions, outputAttributes)
Leftover.

2024-05-08 09:33 UTC, mihak commented on src/stores/attributes/types.ts
> +}
Can't comment on empty file so putting it here.. let's remove `src/stores/attributes/utils.ts`.

2024-05-08 11:07 UTC, sandirezonjaceltra commented on src/main.ts
> +import '@mdi/font/css/materialdesignicons.css'
yes :( for carousel and error

2024-05-08 11:42 UTC, sandirezonjaceltra commented on src/constants.ts
> +    iconUrl: 'https://cache-ssl.celtra.io/api/blobs/128edf2e5f2a9bc4b74c51c1452735fb41595931ea2707e1d84a5b0a05b87ff5/icon.png', // Url to icon needs to be externally available
I dont think this fits in uab codebase, i put it in google drive for now. From github it doesn't work, but still commited it.

2024-05-08 11:49 UTC, sandirezonjaceltra commented on src/views/ExportInfoPanel.vue
> +  <v-expansion-panels class="info">
We don't necessarily have the format label. This was added in initial extension to just output something, and then i answered too late to pero that this isn't really needed and it ended up in design xD

2024-05-08 12:18 UTC, sandirezonjaceltra commented on src/stores/export-api/utils.ts
> +    }
yes, but even though it is not used, i would leave it in the code, since this is an example. Or maybe we add this also?

2024-05-09 11:40 UTC, jkosir reviewed
Do we maybe want to host a bult version of this extension so that users can test it simply by using that url, without having to build and host first?

2024-05-09 11:40 UTC, jkosir commented on README.md
> +3. Host the `index.html` file. As it's a simple html, you can do this in multiple ways - from creating own server to uploading it anywhere that allows file hosting and download. You will need the url
Must be served with text/html mimetype though and must not have any headers preventing embedding in iframe

2024-05-09 11:40 UTC, jkosir commented on src/stores/attributes/store.ts
> +            await celtra.setOutputAttributes(toRaw(this.outputAttributes))
`toRaw` is not needed anymore, right? with the serialization we added. IMO this is just more confusing now

2024-05-09 14:06 UTC, sandirezonjaceltra commented
> Do we maybe want to host a bult version of this extension so that users can test it simply by using that url, without having to build and host first?

Similar to icon - host where if not blobs? :)

2024-05-10 09:36 UTC, mihak commented on src/main.ts
> +import '@mdi/font/css/materialdesignicons.css'
This seems like it adds quite a lot to the size so if it's just 2 icons I would just add them to the code directly and not include everything.

2024-05-10 10:44 UTC, mihak approved these changes

2024-05-10 10:44 UTC, mihak commented on package.json
> +    "@mdi/font": "^7.4.47",
As mentioned in another comment I would avoid including this and just add icons directly - ideally as SVG so if needed Peter can provide them.

2024-05-10 10:44 UTC, mihak commented on src/constants.ts
> +        filterValues: ['Paid Media', 'eCommerce'],
Didn't we change the type to array of strings?
![Screenshot 2024-05-10 at 11 42 35](https://github.com/celtra/custom-ui-extension-template/assets/7932199/bc6f015a-7d42-4376-a5e4-3b1e61e143e2)

2024-05-10 10:44 UTC, mihak commented on src/stores/export-api/store.ts
> +        // Design file might be updated during export, we need to lock to the first content blob hash to guarantee that the export completes.
Much better yes.. maybe just add:
`... to guarantee that the export completes for the same version.`

2024-05-10 10:44 UTC, mihak commented on src/stores/export-api/utils.ts
> +    }
👍 No I think it's fine to leave it in the example.

2024-05-10 10:44 UTC, mihak commented on package.json
> -    "@typescript-eslint/eslint-plugin": "^6.21.0",
Comment for a few lines above. We can probably remove:
`"preview": "vite preview",` and 
`"test": "jest"`
from scripts right?

2024-05-10 10:55 UTC, sandirezonjaceltra commented on src/constants.ts
> +        filterValues: ['Paid Media', 'eCommerce'],
did you update the packages?

2024-05-10 11:46 UTC, mihak commented on src/constants.ts
> +        filterValues: ['Paid Media', 'eCommerce'],
I did later so all good. Ignore :)

2024-05-10 11:52 UTC, sandirezonjaceltra commented on package.json
> +    "@mdi/font": "^7.4.47",
tried adding custom icons. It's a bit of a pain. And we also lose v-select icons (dropdown, clear)

2024-05-13 07:18 UTC, sandirezonjaceltra commented on package.json
> +    "@mdi/font": "^7.4.47",
let's do it in a separate branch if necessary

2024-05-16 06:58 UTC, merged